DROP DATABASE adoption_db;
CREATE DATABASE IF NOT EXISTS adoption_db;
USE adoption_db;

DROP TABLE IF EXISTS `adoption_db`.`PETSHOP` ;

CREATE TABLE IF NOT EXISTS `adoption_db`.`PETSHOP` (
  `PETSHOP_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `LOGO` VARCHAR(45) NULL,
  `ADDRESS` VARCHAR(45) NULL,
  `PHONE_NUM` VARCHAR(45) NULL,
  PRIMARY KEY (`PETSHOP_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoption_db`.`AGENCY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoption_db`.`AGENCY` ;

CREATE TABLE IF NOT EXISTS `adoption_db`.`AGENCY` (
  `AGENCY_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `LOGO` VARCHAR(45) NULL,
  `ADDRESS` VARCHAR(45) NULL,
  `PHONE_NUM` VARCHAR(45) NULL,
  PRIMARY KEY (`AGENCY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoption_db`.`VET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoption_db`.`VET` ;

CREATE TABLE IF NOT EXISTS `adoption_db`.`VET` (
  `VET_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `LOGO` VARCHAR(45) NULL,
  `ADDRESS` VARCHAR(45) NULL,
  `PHONE_NUM` VARCHAR(45) NULL,
  PRIMARY KEY (`VET_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoption_db`.`VOLUNTEER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoption_db`.`VOLUNTEER` ;

CREATE TABLE IF NOT EXISTS `adoption_db`.`VOLUNTEER` (
  `VOLUNTEER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(45) NOT NULL,
  `LASTNAME` VARCHAR(45) NOT NULL,
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `IS_ADMIN` TINYINT(1) NOT NULL,
  `START_TIME` VARCHAR(45) NOT NULL,
  `END_TIME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VOLUNTEER_ID`),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoption_db`.`PET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoption_db`.`PET` ;

CREATE TABLE IF NOT EXISTS `adoption_db`.`PET` (
  `PET_ID` INT NOT NULL AUTO_INCREMENT,
  `PETSHOP_ID` INT NOT NULL,
  `AGENCY_ID` INT NOT NULL,
  `VET_ID` INT NOT NULL,
  `PET_NAME` VARCHAR(45) NOT NULL,
  `PET_TYPE` VARCHAR(45) NOT NULL,
  `PICTURE` VARCHAR(45) NULL,
  `GENDER` VARCHAR(45) NOT NULL,
  `AGE` INT NOT NULL,
  `VOLUNTEER_ID` INT NOT NULL,
  `ADOPTION_PRICE` INT NOT NULL,
  PRIMARY KEY (`PET_ID`),
  INDEX `fk_Pet_PetShop1_idx` (`PETSHOP_ID` ASC) VISIBLE,
  INDEX `fk_Pet_Agency1_idx` (`AGENCY_ID` ASC) VISIBLE,
  INDEX `fk_Pet_Vet1_idx` (`VET_ID` ASC) VISIBLE,
  INDEX `fk_PET_VOLUNTEER1_idx` (`VOLUNTEER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pet_PetShop1`
    FOREIGN KEY (`PETSHOP_ID`)
    REFERENCES `adoption_db`.`PETSHOP` (`PETSHOP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pet_Agency1`
    FOREIGN KEY (`AGENCY_ID`)
    REFERENCES `adoption_db`.`AGENCY` (`AGENCY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pet_Vet1`
    FOREIGN KEY (`VET_ID`)
    REFERENCES `adoption_db`.`VET` (`VET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PET_VOLUNTEER1`
    FOREIGN KEY (`VOLUNTEER_ID`)
    REFERENCES `adoption_db`.`VOLUNTEER` (`VOLUNTEER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoption_db`.`ADOPTER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoption_db`.`ADOPTER` ;

CREATE TABLE IF NOT EXISTS `adoption_db`.`ADOPTER` (
  `ADOPTER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(45) NOT NULL,
  `LASTNAME` VARCHAR(45) NOT NULL,
  `PHONE` VARCHAR(45) NULL,
  `ADDRESS` VARCHAR(45) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `ZIP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ADOPTER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoption_db`.`ADOPTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoption_db`.`ADOPTION` ;

CREATE TABLE IF NOT EXISTS `adoption_db`.`ADOPTION` (
  `PET_ID` INT NOT NULL,
  `ADOPTER_ID` INT NOT NULL,
  `TIME` VARCHAR(45),
  PRIMARY KEY (`PET_ID`),
  INDEX `fk_Adoption_Pet1_idx` (`PET_ID` ASC) VISIBLE,
  INDEX `fk_Adoption_Adopter1_idx` (`ADOPTER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Adoption_Pet1`
    FOREIGN KEY (`PET_ID`)
    REFERENCES `adoption_db`.`PET` (`PET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Adoption_Adopter1`
    FOREIGN KEY (`ADOPTER_ID`)
    REFERENCES `adoption_db`.`ADOPTER` (`ADOPTER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoption_db`.`TIMESLOT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoption_db`.`TIMESLOT` ;

CREATE TABLE IF NOT EXISTS `adoption_db`.`TIMESLOT` (
  `START_TIME` DATETIME NOT NULL,
  `END_TIME` DATETIME NOT NULL,
  `TIMESLOT_ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`TIMESLOT_ID`),
  UNIQUE INDEX `TIMESLOT_ID_UNIQUE` (`TIMESLOT_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoption_db`.`APPOINTMENT_SLOT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoption_db`.`APPOINTMENT_SLOT` ;

CREATE TABLE IF NOT EXISTS `adoption_db`.`APPOINTMENT_SLOT` (
  `VOLUNTEER_ID` INT NOT NULL,
  `TIMESLOT_ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`VOLUNTEER_ID`, `TIMESLOT_ID`),
  INDEX `fk_TIMESLOT_VOLUNTEER1_idx` (`VOLUNTEER_ID` ASC) VISIBLE,
  INDEX `fk_APPOINTMENT_SLOT_TIMESLOT1_idx` (`TIMESLOT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TIMESLOT_VOLUNTEER1`
    FOREIGN KEY (`VOLUNTEER_ID`)
    REFERENCES `adoption_db`.`VOLUNTEER` (`VOLUNTEER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_APPOINTMENT_SLOT_TIMESLOT1`
    FOREIGN KEY (`TIMESLOT_ID`)
    REFERENCES `adoption_db`.`TIMESLOT` (`TIMESLOT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoption_db`.`APPOINTMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoption_db`.`APPOINTMENT` ;

CREATE TABLE IF NOT EXISTS `adoption_db`.`APPOINTMENT` (
  `APPOINTMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `ADOPTER_ID` INT NOT NULL,
  `PET_ID` INT NOT NULL,
  `VOLUNTEER_ID` INT NOT NULL,
  `TIMESLOT_ID` INT NOT NULL,
  PRIMARY KEY (`APPOINTMENT_ID`),
  INDEX `fk_Appointment_Adopter_idx` (`ADOPTER_ID` ASC) VISIBLE,
  INDEX `fk_Appointment_Pet1_idx` (`PET_ID` ASC) VISIBLE,
  INDEX `fk_APPOINTMENT_APPOINTMENT_SLOT1_idx` (`VOLUNTEER_ID` ASC, `TIMESLOT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Adopter`
    FOREIGN KEY (`ADOPTER_ID`)
    REFERENCES `adoption_db`.`ADOPTER` (`ADOPTER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Pet1`
    FOREIGN KEY (`PET_ID`)
    REFERENCES `adoption_db`.`PET` (`PET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_APPOINTMENT_APPOINTMENT_SLOT1`
    FOREIGN KEY (`VOLUNTEER_ID` , `TIMESLOT_ID`)
    REFERENCES `adoption_db`.`APPOINTMENT_SLOT` (`VOLUNTEER_ID` , `TIMESLOT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoption_db`.`SPECIALIZATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoption_db`.`SPECIALIZATIONS` ;

CREATE TABLE IF NOT EXISTS `adoption_db`.`SPECIALIZATIONS` (
  `NAME` VARCHAR(45) NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adoption_db`.`SPECIALIZATIONS_has_VET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adoption_db`.`SPECIALIZATIONS_has_VET` ;

CREATE TABLE IF NOT EXISTS `adoption_db`.`SPECIALIZATIONS_has_VET` (
  `SPECIALIZATIONS_ID` INT NOT NULL AUTO_INCREMENT,
  `VET_VET_ID` INT NOT NULL,
  PRIMARY KEY (`SPECIALIZATIONS_ID`, `VET_VET_ID`),
  INDEX `fk_SPECIALIZATIONS_has_VET_VET1_idx` (`VET_VET_ID` ASC) VISIBLE,
  INDEX `fk_SPECIALIZATIONS_has_VET_SPECIALIZATIONS1_idx` (`SPECIALIZATIONS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_SPECIALIZATIONS_has_VET_SPECIALIZATIONS1`
    FOREIGN KEY (`SPECIALIZATIONS_ID`)
    REFERENCES `adoption_db`.`SPECIALIZATIONS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SPECIALIZATIONS_has_VET_VET1`
    FOREIGN KEY (`VET_VET_ID`)
    REFERENCES `adoption_db`.`VET` (`VET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO VET VALUES(1, "Rochester Vet", "rochester-vet", "26618 Road Ave. Rochester, MI, 48129","(555) 654-4211");
INSERT INTO VET VALUES(2, "Ark Vet", "ark-vet", "26729 Street Ave. Rochester, MI, 48129","(555) 654-1231");
INSERT INTO VET VALUES(3, "Bloomfield Vet", "bloomfield-vet", "33345 Street Rd. Bloomfield Hills, MI, 48439","(555) 654-1231");
INSERT INTO VET VALUES(4, "Farmington Vet", "farmington-vet", "12345 Barn Ave. Farmington, MI, 48113","(555) 624-3411");
INSERT INTO VET VALUES(5, "Macomb Vet", "macomb-vet", "12345 Horse Drive. Macomb, MI, 48113","(555) 612-1231");

INSERT INTO AGENCY VALUES(1, "Canine Friends", "canine-friends", "1234 Paw Lane. Sterling Heights, MI, 48314","(555) 123-1231");
INSERT INTO AGENCY VALUES(2, "Small Pets", "small-pets", "1513 Rabbit Ave. Detroit, MI, 48321","(555) 112-1231");
INSERT INTO AGENCY VALUES(3, "Home For Cats", "home-for-cats", "00912 Boulevard Ave. Shelby, MI, 48316","(555) 123-4256");
INSERT INTO AGENCY VALUES(4, "Fluffball Inc.", "fluffball-inc", "01231 Squirrel Rd. Romeo, MI, 41236","(555) 213-4231");
INSERT INTO AGENCY VALUES(5, "Amphibians R Us", "amphibians", "12311 Pond Rd. Novi, MI, 41236","(555) 223-1231");
INSERT INTO AGENCY VALUES(6, "Birds of a Feather", "birds", "12131 Sky Lane. Lansing, MI, 41236","(555) 323-1123");
INSERT INTO AGENCY VALUES(7, "Underwater Friends", "underwater-friends", "98347 Water Rd. Orion, MI, 41123","(555) 123-1123");

INSERT INTO PETSHOP VALUES(1, "PetSmart", "pet-smart", "54321 Circle Dr. Rochester, MI, 48315", "(333) 120-1260");
INSERT INTO PETSHOP VALUES(2, "Petco", "petco", "89422 Paw Lane. Warren, MI, 45200", "(555) 345-6590");
INSERT INTO PETSHOP VALUES(3, "Quick-Tags", "quick-tags", "78921 Dog Avenue. Armada, MI, 21212", "(333) 777-1234");
INSERT INTO PETSHOP VALUES(4, "Rocko's Petshop", "rocko", "12999 Bell Street. Troy, MI, 21231", "(555) 890-8989");
INSERT INTO PETSHOP VALUES(5, "Pet Haven", "pet-haven", "10291 Animal Ct. Shelby, MI, 48123", "(555) 123-0987");

INSERT INTO VOLUNTEER VALUES(1, "Jim", "Bean", "JBean", "adminPass", 1, "9:00am", "12:00pm");
INSERT INTO VOLUNTEER VALUES(2, "Jack", "Daniel", "JDaniel", "volPass", 0, "9:00am", "12:00pm");
INSERT INTO VOLUNTEER VALUES(3, "Kate", "Louis", "KLouis", "adminPass", 1, "10:15am", "1:15pm");
INSERT INTO VOLUNTEER VALUES(4, "Dave", "Tig", "DTig", "volPass", 0, "9:00am", "12:00pm");
INSERT INTO VOLUNTEER VALUES(5, "Bill", "Row", "BRow", "adminPass", "1", "12:00pm", "3:00pm");
INSERT INTO VOLUNTEER VALUES(6, "Daniel", "Pack", "DPack", "volPass", 0, "10:15am", "1:15pm");
INSERT INTO VOLUNTEER VALUES(7, "Shane", "Black", "SBlack", "adminPass", 1, "12:00pm", "3:00pm");
INSERT INTO VOLUNTEER VALUES(8, "Luke", "Lane", "LLane", "volPass", 0, "10:15am", "1:15pm");
INSERT INTO VOLUNTEER VALUES(9, "Jake", "Lucas", "JLucas", "volPass", 0, "12:00pm", "3:00pm");
INSERT INTO VOLUNTEER VALUES(10, "Blake", "Style", "BStyle", "volPass", 0, "11:30am", "2:30pm");

INSERT INTO PET VALUES(1, 1, 2, 1, "Twinkie", "Dogs", "twinkie", "F", 8, 1, 200);
INSERT INTO PET VALUES(2, 2, 2, 2, "Smores", "Guinea Pigs", "smores", "F", 5, 2, 50);
INSERT INTO PET VALUES(3, 1, 2, 1, "Oreo", "Dogs", "oreo", "M", 7, 3, 210);
INSERT INTO PET VALUES(4, 1, 1, 1, "Vanilla", "Dogs", "vanilla", "M", 5, 4, 200);
INSERT INTO PET VALUES(5, 2, 1, 2, "Stewart Big", "Guinea Pigs", "stewart", "M", 4, 5, 75);
INSERT INTO PET VALUES(6, 2, 1, 2, "Dough Ball", "Guinea Pigs", "doughball", "F", 2, 6, 50);
INSERT INTO PET VALUES(7, 3, 3, 3, "Beth", "Cats", "beth", "F", 6, 7, 190);
INSERT INTO PET VALUES(8, 3, 3, 3, "Snowball", "Cats", "snowball", "M", 6, 8, 200);
INSERT INTO PET VALUES(9, 3, 3, 3, "Mr. Whiskers", "Cats", "mrwhiskers", "M", 8, 9, 210);
INSERT INTO PET VALUES(10, 4, 4, 4, "Mr. Carrots", "Rabbits", "carrots", "M", 9, 10, 500);
INSERT INTO PET	VALUES(11, 4, 4, 4, "Cottontail", "Rabbits", "cottontail", "F", 4, 1, 180);
INSERT INTO PET	VALUES(12, 4, 4, 4, "Thumper", "Rabbits", "thumper", "M", 6, 2, 200);
INSERT INTO PET	VALUES(13, 5, 5, 5, "Croakers", "Frogs", "croakers", "M", 9, 3, 60);
INSERT INTO PET	VALUES(14, 5, 6, 5, "Polly", "Birds", "polly", "M", 10, 4, 300);
INSERT INTO PET	VALUES(15, 5, 7, 5, "Bubbles", "Fish", "bubbles", "F", 2, 5, 80);

INSERT INTO TIMESLOT VALUES('2021-1-4 9:00:00', '2021-1-4 9:15:00', 1);
INSERT INTO TIMESLOT VALUES('2021-1-4 9:30:00', '2021-1-4 9:45:00', 2);
INSERT INTO TIMESLOT VALUES('2021-1-4 10:00:00', '2021-1-4 10:15:00', 3);
INSERT INTO TIMESLOT VALUES('2021-1-4 10:30:00', '2021-1-4 10:45:00', 4);
INSERT INTO TIMESLOT VALUES('2021-1-4 11:00:00', '2021-1-4 11:15:00', 5);
INSERT INTO TIMESLOT VALUES('2021-1-4 11:30:00', '2021-1-4 11:45:00', 6);
INSERT INTO TIMESLOT VALUES('2021-1-4 1:00:00', '2021-1-4 1:15:00', 7);

INSERT INTO ADOPTER	VALUES(1, "Joe", "Doe", "(245)123-345", "56789 Elm Street", "Macomb", "CA", "48065");
INSERT INTO ADOPTER VALUES(2, "Jane", "Phillis", "(234)845-1043", "56790 Elm Street", "Macomb", "CA", "48065");
INSERT INTO ADOPTER	VALUES(3, "Hank", "Johnson", "(890)321-7893", "56789 Elm Street", "Macomb", "CA", "48065");
INSERT INTO ADOPTER	VALUES(4, "Hannah", "Cane", "(123)890-4627", "67092 Sheet Street", "Clinton", "MI", "21890");
INSERT INTO ADOPTER	VALUES(5, "Louis", "Hash", "(253)708-3789", "67080 Sheet Street", "Clinton", "MI", "21890");
INSERT INTO ADOPTER	VALUES(6, "James", "Lipton", "(789)092-2469", "67087 Sheet Street", "Clinton", "MI", "21890");

INSERT APPOINTMENT_SLOT VALUES(1, 1);
INSERT APPOINTMENT_SLOT VALUES(1, 2);
INSERT APPOINTMENT_SLOT VALUES(1, 3);
INSERT APPOINTMENT_SLOT VALUES(1, 4);
INSERT APPOINTMENT_SLOT VALUES(1, 5);
INSERT APPOINTMENT_SLOT VALUES(1, 6);
INSERT APPOINTMENT_SLOT VALUES(1, 7);
INSERT APPOINTMENT_SLOT VALUES(2, 1);
INSERT APPOINTMENT_SLOT VALUES(2, 2);
INSERT APPOINTMENT_SLOT VALUES(2, 3);
INSERT APPOINTMENT_SLOT VALUES(2, 4);
INSERT APPOINTMENT_SLOT VALUES(2, 5);
INSERT APPOINTMENT_SLOT VALUES(2, 6);
INSERT APPOINTMENT_SLOT VALUES(2, 7);
INSERT APPOINTMENT_SLOT VALUES(3, 1);
INSERT APPOINTMENT_SLOT VALUES(3, 2);
INSERT APPOINTMENT_SLOT VALUES(3, 3);
INSERT APPOINTMENT_SLOT VALUES(3, 4);
INSERT APPOINTMENT_SLOT VALUES(3, 5);
INSERT APPOINTMENT_SLOT VALUES(3, 6);
INSERT APPOINTMENT_SLOT VALUES(3, 7);
INSERT APPOINTMENT_SLOT VALUES(4, 1);
INSERT APPOINTMENT_SLOT VALUES(4, 2);
INSERT APPOINTMENT_SLOT VALUES(4, 3);
INSERT APPOINTMENT_SLOT VALUES(4, 4);
INSERT APPOINTMENT_SLOT VALUES(4, 5);
INSERT APPOINTMENT_SLOT VALUES(4, 6);
INSERT APPOINTMENT_SLOT VALUES(4, 7);
INSERT APPOINTMENT_SLOT VALUES(5, 1);
INSERT APPOINTMENT_SLOT VALUES(5, 2);
INSERT APPOINTMENT_SLOT VALUES(5, 3);
INSERT APPOINTMENT_SLOT VALUES(5, 4);
INSERT APPOINTMENT_SLOT VALUES(5, 5);
INSERT APPOINTMENT_SLOT VALUES(5, 6);
INSERT APPOINTMENT_SLOT VALUES(5, 7);
INSERT APPOINTMENT_SLOT VALUES(6, 1);
INSERT APPOINTMENT_SLOT VALUES(6, 2);
INSERT APPOINTMENT_SLOT VALUES(6, 3);
INSERT APPOINTMENT_SLOT VALUES(6, 4);
INSERT APPOINTMENT_SLOT VALUES(6, 5);
INSERT APPOINTMENT_SLOT VALUES(6, 6);
INSERT APPOINTMENT_SLOT VALUES(6, 7);
INSERT APPOINTMENT_SLOT VALUES(7, 1);
INSERT APPOINTMENT_SLOT VALUES(7, 2);
INSERT APPOINTMENT_SLOT VALUES(7, 3);
INSERT APPOINTMENT_SLOT VALUES(7, 4);
INSERT APPOINTMENT_SLOT VALUES(7, 5);
INSERT APPOINTMENT_SLOT VALUES(7, 6);
INSERT APPOINTMENT_SLOT VALUES(7, 7);
INSERT APPOINTMENT_SLOT VALUES(8, 1);
INSERT APPOINTMENT_SLOT VALUES(8, 2);
INSERT APPOINTMENT_SLOT VALUES(8, 3);
INSERT APPOINTMENT_SLOT VALUES(8, 4);
INSERT APPOINTMENT_SLOT VALUES(8, 5);
INSERT APPOINTMENT_SLOT VALUES(8, 6);
INSERT APPOINTMENT_SLOT VALUES(8, 7);
INSERT APPOINTMENT_SLOT VALUES(9, 1);
INSERT APPOINTMENT_SLOT VALUES(9, 2);
INSERT APPOINTMENT_SLOT VALUES(9, 3);
INSERT APPOINTMENT_SLOT VALUES(9, 4);
INSERT APPOINTMENT_SLOT VALUES(9, 5);
INSERT APPOINTMENT_SLOT VALUES(9, 6);
INSERT APPOINTMENT_SLOT VALUES(9, 7);
INSERT APPOINTMENT_SLOT VALUES(10, 1);
INSERT APPOINTMENT_SLOT VALUES(10, 2);
INSERT APPOINTMENT_SLOT VALUES(10, 3);
INSERT APPOINTMENT_SLOT VALUES(10, 4);
INSERT APPOINTMENT_SLOT VALUES(10, 5);
INSERT APPOINTMENT_SLOT VALUES(10, 6);
INSERT APPOINTMENT_SLOT VALUES(10, 7);

INSERT INTO APPOINTMENT VALUE(1, 6, 10, 2, 3);
INSERT INTO APPOINTMENT VALUE(2, 4, 3, 6, 7);

INSERT INTO SPECIALIZATIONS VALUE("Dogs",1);
INSERT INTO SPECIALIZATIONS VALUE("Cats",3);
INSERT INTO SPECIALIZATIONS VALUE("Exotics",5);


INSERT INTO specializations_has_vet VALUE(1, 1);
INSERT INTO specializations_has_vet VALUE(1, 2);
INSERT INTO specializations_has_vet VALUE(1, 3);
INSERT INTO specializations_has_vet VALUE(1, 5);
INSERT INTO specializations_has_vet VALUE(3, 1);
INSERT INTO specializations_has_vet VALUE(3, 4);
INSERT INTO specializations_has_vet VALUE(3, 5);
INSERT INTO specializations_has_vet VALUE(3, 3);
INSERT INTO specializations_has_vet VALUE(5, 2);
INSERT INTO specializations_has_vet VALUE(5, 1);